# Copyright 2024 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("../../../scripts/build/ninja/devtools_entrypoint.gni")
import("../../../scripts/build/ninja/devtools_module.gni")
import("../visibility.gni")

devtools_module("mock") {
  sources = [ "MockPanel.ts" ]

  deps = [
    "../../core/common:bundle",
    "../../core/sdk:bundle",
    "../../models/logs:bundle",
    "../../third_party/codemirror.next:bundle",
    "../../ui/components/code_highlighter:bundle",
    "../../ui/components/text_editor:bundle",
    "../../ui/legacy:bundle",
  ]
}

devtools_entrypoint("bundle") {
  entrypoint = "mock.ts"

  deps = [ ":mock" ]

  visibility = [
    ":*",
    "../../entrypoints/*",
  ]

  visibility += devtools_panels_visibility
}

devtools_entrypoint("meta") {
  entrypoint = "mock-meta.ts"

  deps = [
    ":bundle",
    "../../core/i18n:bundle",
  ]

  visibility = [ "../../entrypoints/*" ]
}
